git:
  depth: 3

language: cpp

compiler:
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    - os: osx
      osx_image: xcode7.3
      sudo: required

addons:
  apt:
    packages:
      - clang
      - ninja-build

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi

install:
  - bash ./.travis/install.sh

script:
  - bash ./.travis/run.sh
